---
title: Title metadata
author:  author
date: "`r Sys.Date()`"
always_allow_html: yes
output:
  html_document:
  number_sections: yes
pdf_document:
  keep_tex: yes
toc: yes
toc_depth: 3
fig_crop: no
template: latex/ETH-IVT_modified/Template.tex
vignette: |
  %\VignetteIndexEntry{Codebook} %\VignetteEngine{knitr::rmarkdown} %\VignetteEncoding{UTF-8}
params:
  datasets:
    value:
      participants:
        file_location: /data/mobis/MOBIS_Covid/tracking/participants.rda
        Title: x
        Contents: >
          This is the description of the file.
          New lines will be compressed into spaces. To have new lines shown,
          use \| instead of \> above. A newline is needed before the next row (in this case title)
        Data collection: x
        Unit of analysis: x
        File structure: x
        Variable Settings:
          hh_postcode: [data_type]
          p_occup_postcode: [data_type]
          hh_yearlydist_car: [data_type, nice_summary, show_histogram]
          day_*: [data_type]
      legs:
        file_location: /data/mobis/MOBIS_Covid/tracking/legs.rda
        Title: legs dataset
        Variable Settings:
          length: [data_type]
          duration: [data_type]

---


# Document description

## Title

  Post-Car World: A multi-stage household survey

## Creator

Gabriel Tilg

Basil Schmid (IVT, ETH Zurich)

## Subject

Codebook, travel diary, online diary, expenditure diary, multi-day reporting period, stated choice, stated adaptation, list of variables

## Description

This document contains a comprehensive codebook for all variables collected as part of series of Post-Car World surveys.

## Publisher

Institute for Transport Planning and Systems (IVT), ETH Zurich

## Contributor

Kay W. Axhausen (IVT, ETH Zurich)

## Date

2019-11-01

## Type

Codebook, surveydata

## Format

Portable document format (pdf), SPSS (.sav)

## Source

https://www.ivt.ethz.ch/en/vpl/travel-research-data.html

## Language

English

## Relation

https://www.ivt.ethz.ch

Details on the survey methods, questionnaire forms, fieldwork, routing algorithms and response behavior can be found in:

  Schmid, B. (2019): \textit{Connecting time-use, travel and shopping behavior: Results of a multi-state household survey}, PhD Thesis, IVT, ETH Zurich, Zurich.

## Coverage

Canton of Zurich, Switzerland, January 2015 - April 2016

## Rights

Institute for Transport Planning and Systems (IVT), ETH Zurich

## Version responsibility

Basil Schmid (IVT, ETH Zurich)


<div style="page-break-after: always; visibility: hidden">
  \clearpage
</div>



  # Study description

  ## Title

  Post-Car World: A multi-stage household survey

## Creator

Basil Schmid (IVT, ETH Zurich)

## Subject

Codebook, travel diary, online diary, expenditure diary, multi-day reporting period, stated choice, stated adaptation, list of variables

## Description

Policy decisions in many developed countries, especially for urban areas, tend to favor car reducing and pedestrian-friendly environments to reduce urban traffic congestion and improve the overall transportation network efficiency. In fact, a technological and behavioral transformation is already under way towards a world with a reduced role of privately owned and operated cars, which are substituted by various forms of shared mobility. The investigation of temporal rhythms in activity scheduling, the reshaping in time organization and mobility tool ownership plays a key role in understanding travel behavior in a world with restricted car ownership and usage, including carsharing and carpooling as potential mode alternatives.

The main research question addressed by this study is to what degree individuals would change travel modes, time allocation and activity patterns after experiencing large changes in generalized transportation costs and how they would react regarding their longer-term ownership in mobility tools, assessing radical pricing effects from an activity-based perspective. The empirical basis is a multi-day travel and online diary that is required to obtain the personalized reference values for the later stated choice and stated adaptation tasks.

## Publisher

Institute for Transport Planning and Systems (IVT), ETH Zurich

## Contributor

Simon Schmutz

Milos Balac (IVT, ETH Zurich)

Kay W. Axhausen (IVT, ETH Zurich)

## Date

2019-11-01

## Type

Codebook, surveydata

## Format

Portable document format (pdf), SPSS (.sav)

## Source

https://www.ivt.ethz.ch/en/vpl/travel-research-data.html

## Language

English

## Relation

https://www.ivt.ethz.ch

Details on the survey methods, questionnaire forms, fieldwork, routing algorithms and response behavior can be found in:

  Schmid, B. (2019): \textit{Connecting time-use, travel and shopping behavior: Results of a multi-state household survey}, PhD Thesis, IVT, ETH Zurich, Zurich.

## Coverage

Canton of Zurich, Switzerland, January 2015 - April 2016

## Rights

Institute for Transport Planning and Systems (IVT), ETH Zurich

## Other identifications, funding and acknowledgements

The authors gratefully thank to the SNSF (Swiss National Science Foundation) for funding the Post-Car World project (grant number 2-77894-13). We also give thanks to Simon Schmutz and Gabriel Tilg, former research assistants at the IVT, for their outstanding contributions to the project.

## Unit of analysis

Household and household members

<div style="page-break-after: always; visibility: hidden">
  \clearpage
</div>

```{r, child = '../inst/rmarkdown/templates/archive_notebook.Rmd'}
```
